version: '3.8'
name: merry-match
services:
  postgres: 
    image: postgres:latest
    container_name: postgres-merry-match
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresql
    volumes:
      - merry_match_volume:/var/lib/postgresql/data
    ports:
      - 2345:5432
    restart: on-failure:5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-merry-match
    environment:
      - PGADMIN_DEFAULT_EMAIL=email@email.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 1234:80
    depends_on:
      - postgres
    restart: on-failure:5

volumes:
  merry_match_volume:
    driver: local