export const previewUserModel = {
  name: "name_test_1",
  username: "username_test_1",
  password: "password",
  birth_date: "1999-01-03",
  location: "Thailand",
  city: "Bangkok",
  email: "username_test_1@email.com",
  sexual_identity: "Male",
  sexual_preference: "Female",
  racial_preference: "Asian",
  meeting_interest: "Partners",
  hobbies: ["1", "2", "3", "4"],
  photos: Array(5).fill(null),
  preview_photos: Array(5).fill(null),
  
  confirm_password: "password",
  about_me: "",
  hobby: "",
};

export const registerUserModel = {
  name: "",
  username: "",
  password: "",
  birth_date: "",
  location: "",
  city: "",
  email: "",
  sexual_identity: "",
  sexual_preference: "",
  racial_preference: "",
  meeting_interest: "",
  hobbies: [],
  photos: Array(5).fill(null),
};